
package main

import "testing"

func TestChallenge(t *testing.T) {
    t.Error() // to indicate test failed
}
